feat: add Mac-style code blocks
doocs/md pull request #183
Opened 2022-08-15 04:56 UTC by YangFong

close #168

2022-08-15 04:58 UTC, YangFong commented
手控配置没写，暂未完成，效果展示：

![image](https://user-images.githubusercontent.com/70502828/184578901-40257bc0-dec8-4de0-94a9-67188f4744db.png)

![image](https://user-images.githubusercontent.com/70502828/184578941-d365af02-87af-4fe2-8f99-c1e41450213d.png)

2022-08-15 06:10 UTC, yanglbme commented
@YangFong 粘贴到公众号，这个样式不生效

2022-08-15 06:16 UTC, YangFong commented
@yanglbme 收到，我找个环境先测试好

2022-08-15 08:10 UTC, YangFong commented
重置样式时，该配置未完善，需要等下一次推送后再合并

2022-08-15 08:15 UTC, yanglbme commented
粘贴时，样式消失了 
![image](https://user-images.githubusercontent.com/21008209/184600288-a48e69af-0ae4-42d2-b91b-876e98936b98.png)

2022-08-15 08:31 UTC, YangFong commented
> ![image](https://user-images.githubusercontent.com/21008209/184600288-a48e69af-0ae4-42d2-b91b-876e98936b98.png)

好奇怪的表现，把标签删了，内容保留。噢，是图片引入的原因，不支持 base64

2022-08-15 08:49 UTC, yanglbme commented
改一下试试

2022-08-15 08:51 UTC, YangFong commented
@yanglbme 替换为 `<svg>` 形式可通过，但是存在一个死角问题，我看能不能收拾了。

2022-08-15 09:10 UTC, YangFong commented
问题：若是代码块是第一行，且前面什么内容都没有，那么就第一个代码块的样式就丢失了。

场景：

可以看到的是，替换是成功的：

![image](https://user-images.githubusercontent.com/70502828/184607669-b24141de-d134-4e3a-a11d-12f8437aefe1.png)

但是在公众号编辑器当中就成了这样，第一个没了：

![image](https://user-images.githubusercontent.com/70502828/184607719-1a242a1a-44a9-4ea4-ad92-582be1e8ce37.png)

2022-08-15 09:19 UTC, yanglbme commented
可以先 push 上来看看

2022-08-15 11:26 UTC, YangFong commented
重置样式已同步修改，但对于文章顶部代码块中的 `<svg>` 消失却看不懂。但凡前面有一个字，都能防止这个现象。

2022-08-15 11:46 UTC, yanglbme commented
是有点奇怪，可以先临时解决一下，比如 `$1<span style="font-size:0">Powered by Doocs</span><svg>......`，或者看没有其他解决方案。

另外，有两个小问题：

1. 一旦导出 .html，页面的代码块圆角立马变成了尖角
2. 三个小圆点能否固定？

2022-08-15 12:17 UTC, YangFong commented
> 是有点奇怪，可以先临时解决一下，比如 `$1<span style="font-size:0">Powered by Doocs</span><svg>......`，或者看没有其他解决方案。
> 
> 另外，有两个小问题：
> 
> 1. 一旦导出 .html，页面的代码块圆角立马变成了尖角
> 2. 三个小圆点能否固定？

这种情况只有代码块在最顶层才触发，我针对这种少数情况，在前方补充一点占位内容，并在页面给与一个弹窗警告，每一次都在附带一些其他生成那不太友好。

其他：

1. 不知道是不是刻意为之，若是只需要保证页面而非 .html 的圆角，可以在导出之后刷新一下即可。
2. 没问题，我尝试使用 `position:sticky` 解决了。

2022-08-15 12:18 UTC, yanglbme commented
嗯嗯，可以，看看效果

2022-08-15 13:43 UTC, yanglbme requested changes

2022-08-15 13:43 UTC, yanglbme commented on src/components/CodemirrorEditor/EditorHeader/index.vue
> +        }
我体验了一下，对用户提示“风险”，还是不太合适。要不这一段先移除吧

2022-08-15 13:43 UTC, yanglbme commented on src/components/CodemirrorEditor/EditorHeader/index.vue
> +            `$1<svg xmlns="http://www.w3.org/2000/svg" width="54" height="14" viewBox="0 0 54 14" style="display: block;position: sticky;left: 0;top: 0;"><g fill="none" fill-rule="evenodd" transform=
position: sticky ，公众号好像不支持，导致没法固定

2022-08-15 14:08 UTC, YangFong commented on src/components/CodemirrorEditor/EditorHeader/index.vue
> +            `$1<svg xmlns="http://www.w3.org/2000/svg" width="54" height="14" viewBox="0 0 54 14" style="display: block;position: sticky;left: 0;top: 0;"><g fill="none" fill-rule="evenodd" transform=
查到了，我再改一下实现方案。这也是闹了，编辑端和手机端还有差别。

2022-08-15 14:10 UTC, YangFong commented on src/components/CodemirrorEditor/EditorHeader/index.vue
> +        }
那就需要整段移除了，也不能在不知情的情况下塞一些内容进入，虽然触发概率挺小的。

2022-08-16 07:07 UTC, YangFong commented
观察到了，不是不能用 `position: sticky`，而是 `position` 完全禁用。会在保存时，自动剔除。

---

又是一个诡异点，我仅仅是开启选择器（仅仅是开启），复制内容的空格就变宽了。

![image](https://user-images.githubusercontent.com/70502828/184818098-d6f06a8c-4340-4588-849a-4536a582b177.png)

关闭选择器，正常尺寸：

![image](https://user-images.githubusercontent.com/70502828/184818241-5011e2db-55b9-46d3-ba6c-237dc0cfe1e4.png)

2022-08-16 08:48 UTC, yanglbme approved these changes

2022-08-16 09:19 UTC, merged