Mac电脑上快捷键特性支持之后，同步菜单显示出正确的快捷键指引｜支持mermaid 啦
doocs/md pull request #250
Opened 2023-11-03 09:09 UTC by bravekingzhang

1. 同步CSS编辑器也支持了Mac上的快捷键啦！
2. 支持显示 mermaid 啦
3. 菜单上的快捷键指引对不上实际快捷键的问题修复啦

2023-11-03 11:07 UTC, yanglbme requested changes

2023-11-03 11:07 UTC, yanglbme commented on src/assets/scripts/config.js
> +};
@bravekingzhang 

感谢提交，这里统一把分号去掉吧

2023-11-03 11:20 UTC, yanglbme commented
@bravekingzhang 有些问题，编辑的过程中，没有及时更新预览。

![image](https://github.com/doocs/md/assets/21008209/8bc79212-075e-4838-9f3a-c61d078e0141)

刷新后才正常显示。

![image](https://github.com/doocs/md/assets/21008209/d12b14f5-ac4d-4729-bf79-8dbb99ce4916)

2023-11-03 11:21 UTC, yanglbme commented
而且一复制，也还原成编辑模式的了。

![image](https://github.com/doocs/md/assets/21008209/b7c57ec4-25d0-4327-a985-e61fbb97afc4)

2023-11-03 12:19 UTC, bravekingzhang commented
@yanglbme  renderer.code  不能写成异步，还是有点麻烦

2023-11-03 12:26 UTC, bravekingzhang commented
@yanglbme 我本地 yarn dev 更本跑不起来，没法调试。

2023-11-03 12:40 UTC, bravekingzhang commented
<img width="1016" alt="image" src="https://github.com/doocs/md/assets/4476322/8f4ebf26-7559-4808-b7c5-6e433b53ad02">
全部搞定啦

2023-11-03 14:05 UTC, YangFong commented on src/assets/scripts/renderers/wx-renderer.js
> -          return `<center>${html}</center>`;
这里不去除似乎也可以。

默认情况下，`$$` 的表现就是居中的。

$$
\large
x=\sqrt{y}+z^2
$$

2023-11-04 02:22 UTC, yanglbme commented
@bravekingzhang 

这里最好不要通过识别 \`\`\`katex``` 的方式渲染公式，而是通过匹配 `$...$` 符号（行内公式）或者 `$$...$$` 符号（块公式）的方式。

这样更加符合 markdown 语法。

2023-11-04 03:02 UTC, bravekingzhang commented
> @bravekingzhang
> 
> 这里最好不要通过识别 ```katex``` 的方式渲染公式，而是通过匹配 `$...$` 符号（行内公式）或者 `$$...$$` 符号（块公式）的方式。
> 
> 这样更加符合 markdown 语法。

你引入的marked似乎没暴露 公式这部分的render呀，一期先这样了，能用就行

2023-11-04 03:38 UTC, yanglbme commented
可以，新加的东西，我先合并，后续可以迭代优化

2023-11-04 03:38 UTC, yanglbme approved these changes

2023-11-04 03:40 UTC, merged

2023-11-04 04:29 UTC, bravekingzhang commented
> 可以，新加的东西，我先合并，后续可以迭代优化

+ 老哥加个微信好友吧

2023-11-04 06:07 UTC, yanglbme commented
可以，我微信是 YLB0109