feat: support for  theme options
doocs/md pull request #326
Opened 2024-08-18 14:47 UTC by YangFong

添加新的预设样式，并提供可选项

2024-08-18 15:04 UTC, yanglbme requested changes

2024-08-18 15:04 UTC, yanglbme commented on src/utils/index.js
> +function createCustomTheme(theme, color, isDefalut = true) {
typo？应该是 isDefault

2024-08-19 00:38 UTC, yanglbme commented
新增的 theme，代码块主题的切换，显示有问题，特别是三个 dark 的代码块样式 @YangFong

2024-08-19 02:06 UTC, YangFong commented
> 新增的 theme，代码块主题的切换，显示有问题，特别是三个 dark 的代码块样式 @YangFong

新主题有改动代码块的样式，主要带来影响的是代码块背景色，所以在表现上和代码块主题不一致。我现在去除了这个背景设定。

2024-08-19 03:05 UTC, yanglbme approved these changes

2024-08-19 03:09 UTC, merged