feat: support GFM alerts & indent code block render pref
doocs/md pull request #446
Opened 2024-11-21 05:17 UTC by dribble-njr

- support [GFM alerts](https://github.com/orgs/community/discussions/16925)
- indent code block render abnomal (mac style or not both)

before:

Indent code render abnormal & don't support GFM.

<img width="667" alt="image" src="https://github.com/user-attachments/assets/1ff8ce7c-4ec5-481e-993d-09d01a4d1a2f">

<img width="658" alt="image" src="https://github.com/user-attachments/assets/675446bd-460d-499e-95e5-c94d09e5ba75">

after:

<img width="642" alt="image" src="https://github.com/user-attachments/assets/1ee283d3-7760-4108-96f6-0471d86d9bd3">

2024-11-21 05:29 UTC, YangFong commented
Need to check preview:

<img width="598" alt="image" src="https://github.com/user-attachments/assets/fa44a89f-9ca4-4137-9ac3-1c9feb445969">

2024-11-21 06:17 UTC, yanglbme commented
是的，无法正常预览

2024-11-21 06:32 UTC, dribble-njr commented
ok，我排查一下

2024-11-21 06:44 UTC, dribble-njr commented
已修复

2024-11-21 11:39 UTC, YangFong commented
测试数据：

```md
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

编辑器可以正常保存并浏览，就是使用比较费劲，必须要全部大写，

在暗色模式下，会有所不搭：

<img width="425" alt="image" src="https://github.com/user-attachments/assets/d5e0c686-23c8-4757-b8fa-2b4908f94c15">

这是在微信浏览中的默认表现，可以做一下暗色预览适配：

<img width="708" alt="image" src="https://github.com/user-attachments/assets/35235f9a-b883-4db8-8c04-eeb9114addbf">

2024-11-21 15:03 UTC, dribble-njr commented
应该可以了，增加了预览的深色模式适配 & 大小写匹配

2024-11-22 00:21 UTC, yanglbme commented
![image](https://github.com/user-attachments/assets/2d97d996-c3e0-4280-9363-b251151c7132)

全大写的情况下，渲染后的文本多了 `[!IMPORTANT]`

2024-11-22 04:45 UTC, yanglbme commented
![image](https://github.com/user-attachments/assets/dc3ab861-b400-4e47-8472-bd6cde01a464)


Caution 我看着不太对

2024-11-22 04:53 UTC, yanglbme requested changes

2024-11-22 04:53 UTC, yanglbme commented on src/assets/example/theme-css.txt
> +}
这几个，如果自定义了，有生效吗

2024-11-22 04:59 UTC, dribble-njr commented on src/assets/example/theme-css.txt
> +}
好像还没生效，我去找找对应的逻辑在哪里

2024-11-22 06:07 UTC, yanglbme commented
看着没啥问题了，准备合并，感谢你的贡献 @dribble-njr

2024-11-22 06:20 UTC, dribble-njr commented
稍等，我准备再做一点优化， @yanglbme 自定义 GFM 样式那块之前的写法有点小问题

2024-11-22 06:35 UTC, yanglbme commented
好

2024-11-22 07:04 UTC, dribble-njr commented
麻烦再看看，这次修复了之前 GFM 块不随字体样式改变的问题，并且优化了他的自定义样式

2024-11-22 07:14 UTC, yanglbme commented
可以

2024-11-22 07:38 UTC, yanglbme approved these changes

2024-11-22 07:39 UTC, merged